n1 = int(input('digite o primeiro número'))
n2 = int(input('digite o segundo número'))
print('O resultado da adição foi ', n1 + n2,) 
print('A subtração foi', n1 - n2)
print('A multiplicação foi', n1 * n2)
print('A divisão foi', round(n1 / n2, 2))